#!/usr/bin/env bash
# =============================================================================
#  setup.sh — Automated Google Cloud SDK Installer for Termux
#  Repository : https://github.com/YOUR_USERNAME/termux-gcloud-setup
#  Target     : Termux on Android → proot-distro Debian → gcloud CLI
#  Author     : Generated by Claude (Anthropic)
#
#  EXECUTION MODEL
#  ---------------
#  This script runs in native Termux but cannot install gcloud there directly
#  because Termux uses a non-standard filesystem prefix. Instead it:
#    1. Installs proot-distro and a Debian rootfs.
#    2. Writes a self-contained "payload" script into that rootfs.
#    3. Executes the payload inside Debian via proot-distro.
#    4. Drops the user into an interactive Debian shell for manual auth.
#
#  STOP POINT
#  ----------
#  `gcloud auth login` is intentionally NOT automated — it requires a
#  manual OAuth browser flow. The script prints clear instructions and
#  hands control back to the user at the right moment.
# =============================================================================

set -euo pipefail

# -----------------------------------------------------------------------------
# ANSI colour helpers
# -----------------------------------------------------------------------------
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
RESET='\033[0m'

# Timestamps for every log line
log()    { echo -e "${DIM}[$(date '+%H:%M:%S')]${RESET} $*"; }
info()   { echo -e "${CYAN}${BOLD}[INFO]${RESET}  $*"; }
ok()     { echo -e "${GREEN}${BOLD}[ OK ]${RESET}  $*"; }
warn()   { echo -e "${YELLOW}${BOLD}[WARN]${RESET}  $*"; }
error()  { echo -e "${RED}${BOLD}[ERR ]${RESET}  $*" >&2; }
die()    { error "$*"; exit 1; }

# -----------------------------------------------------------------------------
# Trap: surface the failing line on unexpected exit
# -----------------------------------------------------------------------------
trap 'error "Script failed at line ${LINENO}. Exit code: $?"; exit 1' ERR

# -----------------------------------------------------------------------------
# Banner
# -----------------------------------------------------------------------------
echo ""
echo -e "${CYAN}${BOLD}"
echo "  ╔════════════════════════════════════════════════════════╗"
echo "  ║        Termux → proot-Debian → gcloud  Installer      ║"
echo "  ║              Cloud Run Deployment Bootstrap            ║"
echo "  ╚════════════════════════════════════════════════════════╝"
echo -e "${RESET}"
echo ""

# -----------------------------------------------------------------------------
# Guard: must be running inside Termux (not plain Linux / CI)
# -----------------------------------------------------------------------------
if [[ -z "${PREFIX:-}" ]]; then
    die "This script must be run inside Termux on Android. \$PREFIX is not set."
fi

if [[ "$PREFIX" != *"com.termux"* ]]; then
    die "Unexpected \$PREFIX value: '$PREFIX'. Are you in Termux?"
fi

info "Termux environment confirmed. PREFIX=${PREFIX}"
echo ""

# -----------------------------------------------------------------------------
# Paths — all derived from Termux's $PREFIX for portability
# -----------------------------------------------------------------------------
DEBIAN_ROOTFS="${PREFIX}/var/lib/proot-distro/installed-rootfs/debian"
PAYLOAD_HOST_PATH="${DEBIAN_ROOTFS}/root/install_gcp.sh"

# =============================================================================
# PHASE 0 — Fix any interrupted dpkg state and upgrade packages
# =============================================================================
echo -e "${BOLD}━━━  Phase 0 of 3: Repairing dpkg & upgrading packages  ━━━${RESET}"
echo ""

info "Running 'dpkg --configure -a' to fix any interrupted package state..."
dpkg --configure -a 2>/dev/null || warn "dpkg --configure -a returned non-zero (may be harmless)."
ok "dpkg state check complete."
echo ""

info "Upgrading existing Termux packages (resolves held-back dependencies)..."
pkg upgrade -y 2>/dev/null || warn "pkg upgrade had warnings — continuing anyway."
ok "Package upgrade complete."
echo ""

# =============================================================================
# PHASE 1 — Install proot-distro in Termux
# =============================================================================
echo -e "${BOLD}━━━  Phase 1 of 3: Installing proot-distro  ━━━${RESET}"
echo ""

if command -v proot-distro &>/dev/null; then
    ok "proot-distro is already installed — skipping."
else
    info "Installing proot-distro via pkg..."
    pkg install -y proot-distro || {
        warn "First attempt failed — trying with --fix-broken..."
        pkg install -y --fix-broken
        pkg install -y proot-distro
    }
    ok "proot-distro installed."
fi
echo ""

# =============================================================================
# PHASE 2 — Bootstrap the Debian rootfs
# =============================================================================
echo -e "${BOLD}━━━  Phase 2 of 3: Bootstrapping Debian rootfs  ━━━${RESET}"
echo ""

if [[ -d "${DEBIAN_ROOTFS}" ]]; then
    ok "Debian rootfs already exists at '${DEBIAN_ROOTFS}' — skipping download."
else
    info "Installing Debian rootfs (this downloads ~300 MB, please wait)..."
    proot-distro install debian
    ok "Debian rootfs installed."
fi
echo ""

# Confirm the rootfs is present before writing the payload
[[ -d "${DEBIAN_ROOTFS}" ]] || \
    die "Debian rootfs missing at '${DEBIAN_ROOTFS}' after install. Aborting."

# =============================================================================
# PHASE 3 — Generate and execute the gcloud payload inside Debian
# =============================================================================
echo -e "${BOLD}━━━  Phase 3 of 3: Generating gcloud install payload  ━━━${RESET}"
echo ""

# ---------------------------------------------------------------------------
# Write the payload script into Debian's /root directory.
# Single-quoted heredoc ('PAYLOAD_EOF') deliberately prevents variable
# expansion here in Termux — all $ references belong to the Debian shell.
# ---------------------------------------------------------------------------
info "Writing payload to: ${PAYLOAD_HOST_PATH}"

cat > "${PAYLOAD_HOST_PATH}" << 'PAYLOAD_EOF'
#!/bin/bash
# ==========================================================================
#  install_gcp.sh — Runs INSIDE proot-distro Debian
#  Do not execute this script directly from Termux.
# ==========================================================================
set -euo pipefail

# ---------- Colour helpers (Debian has no ANSI guarantee by default) ------
CYAN='\033[0;36m'; BOLD='\033[1m'; GREEN='\033[0;32m'
YELLOW='\033[1;33m'; RED='\033[0;31m'; RESET='\033[0m'
info()  { echo -e "${CYAN}${BOLD}[DEBIAN][INFO]${RESET}  $*"; }
ok()    { echo -e "${GREEN}${BOLD}[DEBIAN][ OK ]${RESET}  $*"; }
warn()  { echo -e "${YELLOW}${BOLD}[DEBIAN][WARN]${RESET}  $*"; }
die()   { echo -e "${RED}${BOLD}[DEBIAN][ERR ]${RESET}  $*" >&2; exit 1; }

trap 'die "Payload failed at line ${LINENO}. Exit code: $?"' ERR

echo ""
info "Payload script running inside Debian rootfs."
echo ""

# ---------- 3a: System dependencies ---------------------------------------
info "Updating apt package index..."
apt-get update -y

info "Installing required packages..."
apt-get install -y \
    curl \
    python3 \
    tar \
    ca-certificates || die "apt-get install failed."

# python3-distutils is a separate package in Debian 11 (bullseye) but
# was merged into python3 in Debian 12 (bookworm). Handle both gracefully.
if apt-get install -y python3-distutils 2>/dev/null; then
    ok "python3-distutils installed."
else
    warn "python3-distutils not found (expected on Debian 12+). Python3 base package covers this — continuing."
fi

ok "System dependencies installed."
echo ""

# ---------- 3b: Architecture detection ------------------------------------
ARCH=$(uname -m)
info "Detected CPU architecture: ${ARCH}"

case "${ARCH}" in
    aarch64)
        GCLOUD_PKG="google-cloud-cli-linux-arm.tar.gz"
        ;;
    x86_64)
        GCLOUD_PKG="google-cloud-cli-linux-x86_64.tar.gz"
        ;;
    *)
        die "Unsupported architecture: '${ARCH}'. Only aarch64 and x86_64 are supported."
        ;;
esac

GCLOUD_URL="https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/${GCLOUD_PKG}"
GCLOUD_DEST="/root/${GCLOUD_PKG}"

info "Target tarball : ${GCLOUD_PKG}"
info "Download URL   : ${GCLOUD_URL}"
echo ""

# ---------- 3b (cont): Download the tarball --------------------------------
if [[ -f "${GCLOUD_DEST}" ]]; then
    warn "Tarball already exists at '${GCLOUD_DEST}' — re-using cached file."
    warn "Delete it and re-run if you want a fresh download."
else
    info "Downloading Google Cloud CLI (this may take several minutes)..."
    curl \
        --location \
        --progress-bar \
        --retry 3 \
        --retry-delay 5 \
        --output "${GCLOUD_DEST}" \
        "${GCLOUD_URL}"
    ok "Download complete."
fi
echo ""

# ---------- 3c: Extract and install ----------------------------------------
info "Extracting tarball to /root/..."
tar -xzf "${GCLOUD_DEST}" -C /root/

info "Running gcloud installer (quiet mode, usage reporting disabled)..."
/root/google-cloud-sdk/install.sh \
    --usage-reporting=false \
    --quiet

ok "gcloud SDK installed successfully."
echo ""

# ---------- 3d: Persist PATH into .bashrc ----------------------------------
BASHRC="/root/.bashrc"
SOURCE_LINE="source /root/google-cloud-sdk/path.bash.inc"
COMPLETION_LINE="source /root/google-cloud-sdk/completion.bash.inc"

# Idempotent: only append if the line is not already present
if grep -qF "${SOURCE_LINE}" "${BASHRC}" 2>/dev/null; then
    warn "PATH source line already present in ${BASHRC} — skipping."
else
    echo "" >> "${BASHRC}"
    echo "# Google Cloud SDK — added by install_gcp.sh" >> "${BASHRC}"
    echo "${SOURCE_LINE}" >> "${BASHRC}"
    echo "${COMPLETION_LINE}" >> "${BASHRC}"
    ok "Added gcloud PATH sourcing to ${BASHRC}."
fi

# Immediately source it so gcloud is on PATH for the verification step below
# shellcheck source=/dev/null
source "${SOURCE_LINE#source }" 2>/dev/null || true

echo ""
info "Verifying installation..."
if command -v gcloud &>/dev/null; then
    ok "gcloud binary confirmed on PATH."
    gcloud version
else
    # Non-fatal: installer succeeded but PATH won't refresh until next login
    warn "gcloud not yet on PATH in this sub-shell (normal — source .bashrc on next login)."
    warn "Binary location: /root/google-cloud-sdk/bin/gcloud"
fi

echo ""
echo -e "${GREEN}${BOLD}"
echo "  ┌──────────────────────────────────────────────────────┐"
echo "  │  gcloud CLI installed successfully inside Debian.    │"
echo "  └──────────────────────────────────────────────────────┘"
echo -e "${RESET}"
PAYLOAD_EOF

chmod +x "${PAYLOAD_HOST_PATH}"
ok "Payload script written and marked executable."
echo ""

# ---------------------------------------------------------------------------
# Execute the payload inside Debian via proot-distro
# ---------------------------------------------------------------------------
info "Launching payload inside Debian environment..."
echo -e "${DIM}─────────────────────────── Debian output below ───────────────────────────${RESET}"
echo ""

proot-distro login debian -- bash /root/install_gcp.sh

echo ""
echo -e "${DIM}────────────────────────── Debian output above ────────────────────────────${RESET}"
echo ""

# =============================================================================
# AUTOMATION STOP POINT
# =============================================================================
echo ""
echo -e "${GREEN}${BOLD}"
echo "  ╔════════════════════════════════════════════════════════════╗"
echo "  ║                                                            ║"
echo "  ║   ✓  Google Cloud SDK is ready inside Debian.             ║"
echo "  ║                                                            ║"
echo "  ╚════════════════════════════════════════════════════════════╝"
echo -e "${RESET}"
echo ""
echo -e "${YELLOW}${BOLD}  ──────────────────────────────────────────────────────────${RESET}"
echo -e "${YELLOW}${BOLD}   ACTION REQUIRED — Manual steps inside the Debian shell:${RESET}"
echo -e "${YELLOW}${BOLD}  ──────────────────────────────────────────────────────────${RESET}"
echo ""
echo -e "  ${BOLD}Step 1${RESET} — Activate gcloud on your PATH:"
echo -e "  ${CYAN}    source /root/google-cloud-sdk/path.bash.inc${RESET}"
echo ""
echo -e "  ${BOLD}Step 2${RESET} — Authenticate with Google (no browser launch; paste the URL):"
echo -e "  ${CYAN}    gcloud auth login --no-launch-browser${RESET}"
echo ""
echo -e "  ${BOLD}Step 3${RESET} — Create or set your GCP project:"
echo -e "  ${CYAN}    export PROJECT_ID=\"xray-proxy-\$(date +%Y%m%d)-\$(shuf -i 1000-9999 -n 1)\"${RESET}"
echo -e "  ${CYAN}    gcloud projects create \"\$PROJECT_ID\" --name=\"Xray Proxy\"${RESET}"
echo -e "  ${CYAN}    gcloud config set project \"\$PROJECT_ID\"${RESET}"
echo ""
echo -e "  ${BOLD}Step 4${RESET} — Enable required APIs:"
echo -e "  ${CYAN}    gcloud services enable run.googleapis.com cloudbuild.googleapis.com artifactregistry.googleapis.com${RESET}"
echo ""
echo -e "${YELLOW}${BOLD}  ──────────────────────────────────────────────────────────${RESET}"
echo ""
echo -e "  ${DIM}Dropping you into an interactive Debian shell now...${RESET}"
echo -e "  ${DIM}Type 'exit' to return to Termux at any time.${RESET}"
echo ""

# Drop the user into an interactive Debian session for manual auth
exec proot-distro login debian
